language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
before_script:
  - composer self-update
  - composer install
  - mkdir -p build/logs
script:
  - phpunit -c ./ --coverage-text --coverage-clover build/logs/clover.xml
after_script:
  ## Coveralls
  - php vendor/bin/coveralls -v